export const skills = [
  {
    name: "React.js",
    completed: 100,
    image: "/assets/skills/react.png",
    info: "I have 2 years (not professional) experience with React.js. I specialize in building complex user interfaces and using component-based design effectively.",
    category: "language",
  },
  {
    name: "HTML",
    completed: 100,
    image: "/assets/skills/html.png",
    info: "I have extensive experience in HTML. I can create web pages using advanced HTML5 features in accordance with modern standards.",
    category: "language",
  },
  {
    name: "CSS",
    completed: 95,
    image: "/assets/skills/css.png",
    info: "I have skills in designing with CSS. I can effectively use layout methods such as Flexbox and Grid to create visually appealing and responsive designs.",
    category: "language",
  },
  {
    name: "JavaScript",
    completed: 95,
    image: "/assets/skills/javascript.png",
    info: "About 3 years ago, I entered the world of JavaScript, starting with an understanding of the basic concepts, gaining experience in areas such as DOM manipulation and interaction, API integration, etc. While improving my coding skills with ES6 and beyond, I worked on large projects later with frameworks such as React. Every challenge and success has been part of my continuous learning journey and my enthusiasm for JavaScript has never waned.",
    category: "language",
  },
  {
    name: "Redux / Redux Toolkit",
    completed: 95,
    image: "/assets/skills/redux.png",
    info: "I can work with Redux and Redux Toolkit at an advanced level. I am experienced in global state management and data flow, which facilitates the management of large-scale applications.",
    category: "language",
  },
  {
    name: "Sass",
    completed: 85,
    image: "/assets/skills/sass.png",
    info: "I can use the Sass (SCSS) preprocessor effectively. I am skilled at style-based coding and creating modular structures for reusability.",
    category: "language",
  },
  {
    name: "Tailwind",
    completed: 90,
    image: "/assets/skills/tailwind.png",
    info: "With Tailwind I can use ready-made components and useful classes to build user interfaces quickly and efficiently. Just like I did on this website.",
    category: "language",
  },
  {
    name: "Bootstrap",
    completed: 80,
    image: "/assets/skills/bootstrap.png",
    info: "I can use the Bootstrap framework effectively. My skills in rapid prototyping and responsive design enable me to bring projects to life quickly.",
    category: "language",
  },
  {
    name: "Node.js",
    completed: 75,
    image: "/assets/skills/nodejs.png",
    info: "I have experience developing with Node.js and backend. Although I am not as experienced as frontend, I can use Node.js to create backend services and provide database integration.",
    category: "language",
  },
  {
    name: "Express",
    completed: 75,
    image: "/assets/skills/express.png",
    info: "I can build fast and scalable backend applications using the Express framework. I have experience with RESTful APIs and server-side logic.",
    category: "language",
  },
  {
    name: "MongoDB",
    completed: 75,
    image: "/assets/skills/mongo.png",
    info: "I have skills in data storage and management using the MongoDB database. I can accelerate development processes with its document-based structure.",
    category: "language",
  },
  {
    name: "Typescript",
    completed: 65,
    image: "/assets/skills/typescript.png",
    info: "I can use TypeScript in my projects to write more secure and readable code. I can take advantage of typing and modern JavaScript features. But I am new to TypeScript.",
    category: "language",
  },
  {
    name: "Jest",
    completed: 60,
    image: "/assets/skills/jest.png",
    info: "I only know Jest at a basic level, I'm not very good at testing.",
    category: "language",
  },
];

export const personalSkills = [
  {
    name: "Creativity",
    completed: 100,
    image: "/assets/skills/creativity.png",
    info: "Creativity is a skill that makes projects unique and impressive. I can produce original solutions by offering different perspectives in design and coding processes.",
    category: "personal",
  },
  {
    name: "Communication",
    completed: 95,
    image: "/assets/skills/communication.png",
    info: "Good communication enables to collaborate effectively within the team. I am skilled at explaining technical terms clearly and sharing ideas.",
    category: "personal",
  },
  {
    name: "Open to learn",
    completed: 100,
    image: "/assets/skills/open-to-learn.png",
    info: "Being open to continuous learning and development is one of my greatest strengths as a junior developer. I enjoy learning new technologies.",
    category: "personal",
  },
  {
    name: "Problem Solving",
    completed: 95,
    image: "/assets/skills/puzzle.png",
    info: "Solving problems is a fundamental part of the software development process. I can use my analytical thinking skills to find solutions when faced with challenges.",
    category: "personal",
  },
  {
    name: "Team Work",
    completed: 92,
    image: "/assets/skills/team-work.png",
    info: "Collaboration in a team is essential for successful projects. I can work harmoniously with people from different areas of expertise.",
    category: "personal",
  },
  {
    name: "Time Management",
    completed: 90,
    image: "/assets/skills/time-management.png",
    info: "Time management is a critical skill to complete projects efficiently. I can prioritize tasks and stick to deadlines.",
    category: "personal",
  },
  {
    name: "Adaptation",
    completed: 95,
    image: "/assets/skills/adaptation.png",
    info: "Adaptability is important in a rapidly changing technology environment. I can quickly adapt to new conditions and requirements.",
    category: "personal",
  },
];

export const developerSkills = [
  {
    name: "Web Development",
    completed: 100,
    image: "/assets/skills/web.webp",
    info: "I think I have a good, if not professional, experience in web development. I can create user-friendly and functional web applications using frontend and backend technologies.",
    category: "developer",
  },
  {
    name: "Rest API Entegration",
    completed: 100,
    image: "/assets/skills/api.png",
    info: "I can effectively integrate RESTful APIs. I am skilled in making API calls and processing responses for data exchange.",
    category: "developer",
  },
  {
    name: "Git Version Control",
    completed: 93,
    image: "/assets/skills/git.png",
    info: "I can effectively manage version control and collaboration using Git. I am experienced in organizing the codebase by creating and merging various branches.",
    category: "developer",
  },
  {
    name: "DB Management",
    completed: 90,
    image: "/assets/skills/db.png",
    info: "I have skills in database administration. Although I have little experience with SQL, I can work with NoSQL databases and have experience in data processing and storage.",
    category: "developer",
  },
  {
    name: "Testing and Debugging",
    completed: 60,
    image: "/assets/skills/test.png",
    info: "I try to do my best in testing and debugging. I can still test and debug code using testing frameworks like Jest.",
    category: "developer",
  },
];

export const projects = [
  {
    name: "GPT",
    description: "A landing page template introducing GPT.",
    pageUrl: "https://anz-gpt.onrender.com",
    codeUrl: "https://github.com/Anzcyent/anz-gpt/tree/main",
    image: "/assets/projects/gpt.png",
    category: "landing",
    techStacks: ["/assets/skills/react.png", "/assets/skills/sass.png"],
  },
  {
    name: "PolyZone",
    description:
      "A landing page template introducing a shooting range shop that I've created for one of my friends.",
    pageUrl: "https://poly-zone.onrender.com",
    codeUrl: "https://github.com/Anzcyent/poly-zone",
    image: "/assets/projects/polyzone.png",
    category: "landing",
    techStacks: ["/assets/skills/react.png", "/assets/skills/sass.png"],
  },
  {
    name: "FitFlex",
    description: "A landing page template introducing a GYM chain company.",
    pageUrl: "https://fit-flex.onrender.com",
    codeUrl: "https://github.com/Anzcyent/fitflex",
    image: "/assets/projects/fitflex.png",
    category: "landing",
    techStacks: [
      "/assets/skills/react.png",
      "/assets/skills/sass.png",
      "/assets/skills/swiper.png",
    ],
  },
  {
    name: "ShopEazy",
    description: "A full stack (MERN) e-commerce website.",
    pageUrl: "https://shopeazy-client.onrender.com",
    codeUrl: [
      "https://github.com/Anzcyent/e-commerce-client",
      "https://github.com/Anzcyent/e-commerce-server",
    ],
    image: "/assets/projects/shopeazy.png",
    category: "full-stack",
    techStacks: [
      "/assets/skills/react.png",
      "/assets/skills/tailwind.png",
      "/assets/skills/redux.png",
      "/assets/skills/nodejs.png",
      "/assets/skills/mongo.png",
      "/assets/skills/axios.png",
    ],
  },
  {
    name: "BlogAnz",
    description:
      "A full stack (MERN) blog sharing website that I've created for my school project.",
    pageUrl: "https://bloganz-client.onrender.com",
    codeUrl: [
      "https://github.com/Anzcyent/bloganz-client",
      "https://github.com/Anzcyent/bloganz-server",
    ],
    image: "/assets/projects/bloganz.png",
    category: "full-stack",
    techStacks: [
      "/assets/skills/react.png",
      "/assets/skills/tailwind.png",
      "/assets/skills/redux.png",
      "/assets/skills/nodejs.png",
      "/assets/skills/mongo.png",
      "/assets/skills/axios.png",
    ],
  },
  {
    name: "Vote Vortex",
    description: "A full stack (MERN) survey sharing website.",
    pageUrl: "https://vote-vortex-client.onrender.com",
    codeUrl: [
      "https://github.com/Anzcyent/vote-vortex-client",
      "https://github.com/Anzcyent/vote-vortex-server",
    ],
    image: "/assets/projects/votevortex.png",
    category: "full-stack",
    techStacks: [
      "/assets/skills/react.png",
      "/assets/skills/tailwind.png",
      "/assets/skills/redux.png",
      "/assets/skills/nodejs.png",
      "/assets/skills/mongo.png",
      "/assets/skills/axios.png",
    ],
  },
  {
    name: "Guess What",
    description:
      "A full stack (MERN) and basic gambling (for entertainment purposes, no real money is used) game.",
    pageUrl: "https://guess-what-client.onrender.com",
    codeUrl: [
      "https://github.com/Anzcyent/guess-what-client",
      "https://github.com/Anzcyent/guess-what-server",
    ],
    image: "/assets/projects/guesswhat.png",
    category: "full-stack",
    techStacks: [
      "/assets/skills/react.png",
      "/assets/skills/tailwind.png",
      "/assets/skills/redux.png",
      "/assets/skills/nodejs.png",
      "/assets/skills/mongo.png",
      "/assets/skills/axios.png",
    ],
  },
];
